#!/usr/bin/env tsx
/**
 * Codestral Review Script
 *
 * Reads git diff, sends to Mistral Codestral for:
 * - Edge-case test suggestions
 * - Invariant ideas
 * - Security checklist
 *
 * Writes output to docs/reviews/<timestamp>-codestral.md
 */

import { execSync } from "child_process";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const MISTRAL_API_KEY = process.env.MISTRAL_API_KEY;
const CODESTRAL_ENDPOINT =
  "https://codestral.mistral.ai/v1/chat/completions";

if (!MISTRAL_API_KEY) {
  console.error("ERROR: MISTRAL_API_KEY not set");
  console.error("Set it in .env or export it before running this script.");
  process.exit(1);
}

async function getDiff(): Promise<string> {
  try {
    const diff = execSync("git diff HEAD~1", { encoding: "utf-8" });
    if (!diff.trim()) {
      return execSync("git diff --cached", { encoding: "utf-8" });
    }
    return diff;
  } catch {
    console.warn("No git diff available, using staged changes");
    return execSync("git diff --cached", { encoding: "utf-8" });
  }
}

async function reviewWithCodestral(diff: string): Promise<string> {
  const prompt = `You are a Solidity security reviewer. Analyze this git diff and provide:

1. **Edge-case tests** (Foundry format): 3-5 test functions covering boundary conditions
2. **Invariant ideas**: 2-3 invariants that should hold across all states
3. **Security checklist**: Check for reentrancy, overflow, access control, front-running, oracle manipulation

Be concise. Output in markdown.

\`\`\`diff
${diff.slice(0, 8000)}
\`\`\``;

  const response = await fetch(CODESTRAL_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${MISTRAL_API_KEY}`,
    },
    body: JSON.stringify({
      model: "codestral-latest",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 2000,
      temperature: 0.3,
    }),
  });

  if (!response.ok) {
    throw new Error(`Codestral API error: ${response.status} ${response.statusText}`);
  }

  const data = (await response.json()) as {
    choices: Array<{ message: { content: string } }>;
  };
  return data.choices[0]?.message?.content ?? "No response from Codestral";
}

async function main() {
  console.log("==> Codestral Review Script");

  const diff = await getDiff();
  if (!diff.trim()) {
    console.log("No changes to review.");
    process.exit(0);
  }

  console.log(`Diff size: ${diff.length} chars`);
  console.log("Sending to Codestral for review...");

  const review = await reviewWithCodestral(diff);

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const outDir = join(process.cwd(), "docs", "reviews");
  mkdirSync(outDir, { recursive: true });

  const outPath = join(outDir, `${timestamp}-codestral.md`);
  const content = `# Codestral Review — ${new Date().toISOString()}

## Diff Summary
- Characters: ${diff.length}
- Generated by: \`scripts/verifier/codestral_review.ts\`

## Review

${review}
`;

  writeFileSync(outPath, content);
  console.log(`Review written to: ${outPath}`);
}

main().catch((err) => {
  console.error("Review failed:", err);
  process.exit(1);
});
